name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear GitHub Actions Cache
        run: |
          npm cache clean --force
        env:
          CI: true

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build
        run: |
          cd client
          npm run build

      - name: Move files to 'docs' directory
        run: |
          mv client/dist/* docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        env:
          deploy_key: ${{secrets.FIRST_DEPLOY_KEY}}
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./docs
